require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DocumentBindersController do

  # This should return the minimal set of attributes required to create a valid
  # DocumentBinder. As you add validations to DocumentBinder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DocumentBindersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all document_binders as @document_binders" do
      document_binder = DocumentBinder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:document_binders).should eq([document_binder])
    end
  end

  describe "GET show" do
    it "assigns the requested document_binder as @document_binder" do
      document_binder = DocumentBinder.create! valid_attributes
      get :show, {:id => document_binder.to_param}, valid_session
      assigns(:document_binder).should eq(document_binder)
    end
  end

  describe "GET new" do
    it "assigns a new document_binder as @document_binder" do
      get :new, {}, valid_session
      assigns(:document_binder).should be_a_new(DocumentBinder)
    end
  end

  describe "GET edit" do
    it "assigns the requested document_binder as @document_binder" do
      document_binder = DocumentBinder.create! valid_attributes
      get :edit, {:id => document_binder.to_param}, valid_session
      assigns(:document_binder).should eq(document_binder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocumentBinder" do
        expect {
          post :create, {:document_binder => valid_attributes}, valid_session
        }.to change(DocumentBinder, :count).by(1)
      end

      it "assigns a newly created document_binder as @document_binder" do
        post :create, {:document_binder => valid_attributes}, valid_session
        assigns(:document_binder).should be_a(DocumentBinder)
        assigns(:document_binder).should be_persisted
      end

      it "redirects to the created document_binder" do
        post :create, {:document_binder => valid_attributes}, valid_session
        response.should redirect_to(DocumentBinder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved document_binder as @document_binder" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBinder.any_instance.stub(:save).and_return(false)
        post :create, {:document_binder => { "code" => "invalid value" }}, valid_session
        assigns(:document_binder).should be_a_new(DocumentBinder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBinder.any_instance.stub(:save).and_return(false)
        post :create, {:document_binder => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested document_binder" do
        document_binder = DocumentBinder.create! valid_attributes
        # Assuming there are no other document_binders in the database, this
        # specifies that the DocumentBinder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DocumentBinder.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => document_binder.to_param, :document_binder => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested document_binder as @document_binder" do
        document_binder = DocumentBinder.create! valid_attributes
        put :update, {:id => document_binder.to_param, :document_binder => valid_attributes}, valid_session
        assigns(:document_binder).should eq(document_binder)
      end

      it "redirects to the document_binder" do
        document_binder = DocumentBinder.create! valid_attributes
        put :update, {:id => document_binder.to_param, :document_binder => valid_attributes}, valid_session
        response.should redirect_to(document_binder)
      end
    end

    describe "with invalid params" do
      it "assigns the document_binder as @document_binder" do
        document_binder = DocumentBinder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBinder.any_instance.stub(:save).and_return(false)
        put :update, {:id => document_binder.to_param, :document_binder => { "code" => "invalid value" }}, valid_session
        assigns(:document_binder).should eq(document_binder)
      end

      it "re-renders the 'edit' template" do
        document_binder = DocumentBinder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBinder.any_instance.stub(:save).and_return(false)
        put :update, {:id => document_binder.to_param, :document_binder => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested document_binder" do
      document_binder = DocumentBinder.create! valid_attributes
      expect {
        delete :destroy, {:id => document_binder.to_param}, valid_session
      }.to change(DocumentBinder, :count).by(-1)
    end

    it "redirects to the document_binders list" do
      document_binder = DocumentBinder.create! valid_attributes
      delete :destroy, {:id => document_binder.to_param}, valid_session
      response.should redirect_to(document_binders_url)
    end
  end

end
